baseURL = "yagud.in/"
languageCode = "en-us"
title = "Misha's personal webpage"
theme = "yinyang"
DefaultContentLanguage = "en"

[author]
  name = "Misha Yagudin"


[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.ru]
    contentDir = "content/ru"
    languageName = "Russian"
    weight = 2


[[params.socials]]
name = "Github"
link = "https://github.com/yagudin"

[[params.socials]]
name = "Twitter"
link = "https://twitter.com/mishayagudin"

[params]
extraHead = '<script src="xxxx.js"></script>'

exclude: ['hemes/yinyang/exampleSite/content/en/post/migrate-from-jekyll.md']
